apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mimir
  namespace: mimir
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
