# Default values for guacamole.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

guacamole:
  image:
    repository: guacamole/guacamole
    tag: "latest"
    pullPolicy: IfNotPresent
  # Key-value settings directly passed as environment variables
  settings:
    SAML_CALLBACK_URL: <path:christof#saml-callback-url>
    SAML_ENTITY_ID: <path:christof#saml-entity-id>
    SAML_IDP_URL: <path:christof#saml-idp-url>
    SAML_IDP_METADATA_URL: <path:christof#saml-idp-metadata-url>
    SAML_STRICT: "false"
    EXTENSION_PRIORITY: "saml"

guacd:
  image:
    repository: guacamole/guacd
    tag: "latest"
    pullPolicy: IfNotPresent

dbcreation:
  image:
    repository: bitnami/postgresql
    tag: 14.3.0-debian-10-r9
    pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
  hosts:
        - host: <path:christof#guacamole-host>
      paths: 
        - "/"

  tls: 
    - secretName: <path:christof#ingress-secret-name>
      hosts:
              - <path:christof#guacamole-host>

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

postgres:
  hostname: "postgres-postgresql"
  port: "5432"
  database: "guacamole"
  user: "guacamole"
  password: <path:christof#postgress-password>
